### ISSUE TITLE
Naming rules not followed

### ISSUE THREAD

**Issue by bedsheet-insane** [xuejianxianzun/PixivFanboxDownloader#60]
When downloading, the naming rules are not followed (i.e. no subfolders created, names not changed according to rules). Instead, the original file names are used, and all files are saved in the browser's download folder.

**Comment by xuejianxianzun** [comment]
The problem with abnormal file names

Certain extensions take over the browser's downloads, so the downloads I set up will be handled by them, possibly losing the filenames I set.

There are a lot of these extensions (even if they are not running on Pixiv and Fanbox will cause this problem). In recent feedback, the extension causing this issue is usually Patreon Downloader.

If the downloaded file name is unusual, please disable such extensions while downloading.
